bookReviewBlog/bookPosts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from bookReviewBlog import db
from bookReviewBlog.models import BlogPost
from bookReviewBlog.bookPosts.forms import BookPostForm

bookPosts = Blueprint('bookPosts', __name__)

# create a post
@bookPosts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BookPostForm()
    if form.validate_on_submit():
        blogPost = BlogPost(title=form.title.data,
                            text=form.text.data,
                            userId=current_user.id)
        db.session.add(blogPost)
        db.session.commit()
        flash('blog post created')
        return redirect(url_for('core.index'))
    return render_template('createPost.html', form=form)


# view a post
@bookPosts.route('/<int:blogPostID>')
def blogPost(blogPostID):
    blogPost = BlogPost.query.get_or_404(blogPostID)
    return render_template('blogPostView.html', title=blogPost.title, date=blogPost.date, post=blogPost)


# update
@bookPosts.route('/<int:blogPostID>/update', methods=['GET', 'POST'])
@login_required
def update(blogPostID):
    blogPost = BlogPost.query.get_or_404(blogPostID)
    if blogPost.author != current_user:
        abort(403)
    form = BookPostForm()
    if form.validate_on_submit():
        blogPost.title=form.title.data
        blogPost.text=form.text.data

        db.session.commit()
        flash('blog post updated')
        return redirect(url_for('bookPosts.blogPost', blogPostID=blogPost.id))
    elif request.method == 'GET':
        form.title.data = blogPost.title
        form.text.data = blogPost.text
    return render_template('createPost.html', title='Updating', form=form)


# delete
@bookPosts.route('/<int:blogPostID>/delete', methods=['GET', 'POST'])
@login_required
def deletePost(blogPostID):
    blogPost = BlogPost.query.get_or_404(blogPostID)
    if blogPost.author != current_user:
        abort(403)
    
    db.session.delete(blogPost)
    db.session.commit()
    flash('blog post deleted')
    return redirect(url_for('core.index'))
    

bookReviewBlog/core/views.py
from flask import render_template, request, Blueprint
from bookReviewBlog.models import BlogPost
core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

bookReviewBlog/users/views.py
# views for the users
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from bookReviewBlog import db
from bookReviewBlog.models import User, BlogPost
from bookReviewBlog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from bookReviewBlog.users.pictureHandler import add_profile_pic

users = Blueprint('users', __name__)

# register
@users.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # if the form is valid then get the user
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Login Success!')

            # checks if the user was trying to reach a page that required a dead login
            next = request.args.get('next')
            if next==None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html', form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

#
# the users account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        # if they add a picture to their account
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profilePics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


# the users list of blog posts
@users.route("/<username>")
def userPosts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('userBlogPosts.html', blog_posts=blog_posts, user=user)

bookReviewBlog/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron" style="background-color: #E1D4DD;"> 
        <div align='center'>
            <h1>Welcome to the page for {{current_user.username}}</h1>
            <img align='center' src="{{url_for('static', filename='profilePics/'+current_user.profile_image)}}">
        </div>
    </div>

    <div class="container"> 
        <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.username.label(class='form-group')}}{{form.username(class='form-control')}}
            </div>
            <div class="form-group">
                {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
            </div>
            <div class="form-group">
                {{form.picture.label(class='form-group')}}{{form.picture(class='form-control')}}
            </div>
            <div class="form-group">
                {{form.submit(class='btn btn-primary')}}
            </div>
            
        </form>
    </div>
{% endblock %}

bookReviewBlog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir=""ltr>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <meta charset="UTF-8">
        <title>Document</title>
    </head>
    <body>
        <ul class="nav" style="background-color: #E0BA61;">
            <li class="nav-link">
                <a href="{{url_for('core.index')}} " style="color: #241E4E;">Home</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('core.info')}}" style="color: #241E4E;">About</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-link">
                <a href="{{url_for('users.logout')}} " style="color: #241E4E;">Logout</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.account')}}" style="color: #241E4E;">Account</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('bookPosts.create_post')}}" style="color: #241E4E;">Write a Review!</a>
            </li>
            {% else %}
            <li class="nav-link">
                <a href="{{url_for('users.login')}}" style="color: #241E4E;">Login</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.register')}}" style="color: #241E4E;">Register</a>
            </li>
            {% endif %}
        </ul>
        <div class="container" style="background-color:#E1D4DD;">
            {% block content %}
            
            {% endblock %}
        </div>
    </body>
</html>

bookReviewBlog/templates/blogPostView.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron" style="background-color: #E1D4DD;">
    <h1>{{ post.title }}</h1>
    <h2>Written by: {{post.author.username}}</h2>
    <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
    <p>{{post.text}}</p>
    {% if post.author == current_user %}
        <div>
        <a class="btn btn-secondary" href="{{ url_for('bookPosts.update', blogPostID=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
        </div>
    {% endif %}
</div>




<!-- Modal for Pop Up-->
{# https://getbootstrap.com/docs/4.1/components/modal/ #}
{# Notice how the link with the id to the button above! #}
<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title">Delete Post Pop up Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
        <p>Are you sure you want to delete this review?</p>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{ url_for('bookPosts.deletePost', blogPostID=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
        </div>
    </div>
    </div>
</div>

{% endblock content %}

bookReviewBlog/templates/createPost.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div style="display: flex; justify-content: center; align-items:center;  padding: 20px;">
    <h1>Write a book review!</h1>
  </div>
  <form class="form-group" method="POST" style="padding: 10px;">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info", style="color: #E1D4DD; background-color: #241E4E;") }}
     </div>
  </form>

</div>

{% endblock content %}

bookReviewBlog/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron"  style="text-align: center; background-color:#E1D4DD;" > 
        <h1> Welcome to BookBuzz! 🐝 </h1>
        <h3> Explore the honeycomb of treasured works!</h3>
    </div>

    <div class="container">

        {# Go through each blog post #}
        {% for post in blog_posts.items %}
    
        <div class="card" style="background-color: #E0918B; border-radius: 25px; margin: 10px; border-color: #241E4E; border-width: 2px;">
    
            <div class="card-body">
    
    
            <h2><a class="card-title" href="  {{ url_for('bookPosts.blogPost', blogPostID=post.id) }}" style="color: #241E4E;">{{ post.title }}</a></h2>
            <a href="{{ url_for('users.userPosts', username=post.author.username) }}" style="color: #6B0504">Written By: {{ post.author.username }}</a>
            <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
            <p class="card-text">{{ post.text[:100] }}...</p>
            <a href="{{ url_for('bookPosts.blogPost', blogPostID=post.id) }}" class="btn btn-primary" style="color: #E1D4DD; background-color: #241E4E;">Read Review!</a>
            </div>
        </div>
    
        {% endfor %}
    
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if blog_posts.page == page_num %}
                <li class="page-item disabled" >
                <a class="page-link" href="{{ url_for('core.index', page=page_num) }}" style="color: #E1D4DD; background-color: #241E4E;">{{ page_num }}</a></li>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}" style="color: #241E4E; background-color: #F2EFF1; border-color: #241E4E; border-radius: 2px;" >{{ page_num }}</a></li>
                {% endif %}
            {% endfor %}
        </nav>
{% endblock %}

bookReviewBlog/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron" style="text-align: center; background-color:#E1D4DD; "> 
        <h1> Discover a world of beloved books at BookBuzz! 📖✨ </h1>
        <h4>Login and write about your favorite literary works! </h4>
        <p> 
            <br>This is a collection where people post reviews of their favorite books. You can add tags to your review and find other books with a similar genre or theme. 
            <br>Get book inspiration from other people's reviews, and never run out of extraordinary books to explore.   
        </p>
    </div>
{% endblock %}

bookReviewBlog/templates/login.html
{%extends "base.html" %}
{% block content %}
    <form method="POST" style="padding: 20px;">
        {{form.hidden_tag()}}
        <div style="display: flex; justify-content: center; align-items:center; margin: 20px">
            <h1>Login</h1>
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            <label for="emailLabel">Email address</label>
            {{ form.email(class_="form-control", id="inputEmail", placeholder="Enter email") }}
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            <label for="passwordLabel">Password</label>
            {{form.password (class_="form-control", id="inputPassword", placeholder="Password") }}
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            {{form.submit()}}
        </div>
        <!-- {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.submit()}} -->
    </form>

{% endblock %}

bookReviewBlog/templates/register.html
{%extends "base.html" %}
{% block content %}
    <form method="POST" style="padding: 20px;">
        {{form.hidden_tag()}}
        <div style="display: flex; justify-content: center; align-items:center;  margin: 20px;">
        <h1>Register your account!</h1>
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            <label for="emailLabel">Email address</label>
            {{ form.email(class_="form-control", id="inputEmail", placeholder="Enter your email") }}
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            <label for="usernameLabel">Username</label>
            {{form.username (class_="form-control", id="inputUsername", placeholder="Set a username!") }}
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            <label for="passwordLabel">Password</label>
            {{form.password (class_="form-control", id="inputPassword", placeholder="Password") }}
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            <label for="passwordConfirmLabel">Confirm Password</label>
            {{form.pass_confirm (class_="form-control", id="inputPasswordConfirm", placeholder="Confirm Password") }}
        </div>
        <div class="form-group" style="align-items:center; margin-left: 25%; margin-right: 25%;">
            {{form.submit()}}
        </div>
        <!-- {{form.email.label}}{{form.email}}<br>
        {{form.username.label}}{{form.username}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.pass_confirm.label}}{{form.pass_confirm}}<br> -->
        <!-- {{form.submit()}} -->
    </form>

{% endblock %}

bookReviewBlog/templates/userBlogPosts.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="jumbotron" style="background-color: #E1D4DD;"> 
            <div align="center">
                <h1>Welcome to the page for {{user.username}}</h1>
                <img src="{{url_for('static',filename='profilePics/'+user.profile_image)}}">
            </div>
        </div>
    

        {% for post in blog_posts.items %}
        <h2> 
            <a href="{{url_for('bookPosts.blogPost',blogPostID=post.id)}}">{{post.title}}</a>
        </h2>
        Written By: <a href="{{url_for('users.userPosts', username=post.author.username)}}">{{post.author.username}}</a>
        <p class="'text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
        <br>
        <p>{{post.text}}</p>
        {% endfor %}
    </div>
    
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% for post in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
                {% if blog_posts.page == page_num %}
                    <li class="page-item disabled">
                        <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}" style="color: #E1D4DD; background-color: #241E4E;">{{page_num}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{url_for('users.userPosts', username=user.username, page=page_num)}}" style="color: #241E4E; background-color: #F2EFF1; border-color: #241E4E; border-radius: 2px;">{{page_num}}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
      </nav>
{% endblock %}